//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20MCA121
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Master
    {
        public int User_id { get; set; }
        public string User_name { get; set; }
        public string User_Password { get; set; }
    }
}
